apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
          env:
            - name: discovery.type
              value: single-node # Set this for single-node deployment
            - name: xpack.security.enabled
              value: "false" # Disable security features

          ports:
            - containerPort: 9200
              name: http
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
        - name: metricbeat
          image: docker.elastic.co/beats/metricbeat:8.10.0
          env:
            - name: ELASTICSEARCH_HOST
              value: "http://localhost:9200"
          volumeMounts:
            - name: metricbeat-config
              mountPath: /etc/metricbeat
      volumes:
        - name: data
          emptyDir: {}
        - name: metricbeat-config
          configMap:
            name: metricbeat-config
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: default
spec:
  ports:
    - port: 9200
      targetPort: 9200
  selector:
    app: elasticsearch
