apiVersion: v1
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/lib/docker/containers/*/*.log
      processors:
        - add_kubernetes_metadata:
            in_cluster: true
        - drop_event:
            when:
              not:
                equals:
                  kubernetes.labels.app: "stock-app"

    output.elasticsearch:
      hosts: ["http://elasticsearch:9200"]

    # Logging configuration
    logging:
      level: info           # Options: debug, info, warning, error, critical
      to_files: true         # Logs will be written to files
      files:
        path: /var/log/filebeat  # Location where log files will be saved (ensure the directory exists or is writable)
        name: filebeat        # Log file name
        keepfiles: 7          # Keep logs for the past 7 days
        permissions: 0644     # Ensure the permissions allow Filebeat to write to the file

kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: default
