apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: kube-system
  labels:
    k8s-app: fluent-bit
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit
  template:
    metadata:
      labels:
        k8s-app: fluent-bit
    spec:
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: config-volume
              mountPath: /fluent-bit/etc
              subPath: fluent-bit.conf
            - name: log-volume
              mountPath: /var/log
            - name: var-run
              mountPath: /var/run
            - name: fluent-bit-plugins
              mountPath: /fluent-bit/plugins
      volumes:
        - name: config-volume
          configMap:
            name: fluent-bit-config
        - name: log-volume
          hostPath:
            path: /var/log
            type: Directory
        - name: var-run
          hostPath:
            path: /var/run
            type: Directory
        - name: fluent-bit-plugins
          emptyDir: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: kube-system
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info
        Daemon       Off

    [INPUT]
        Name         tail
        Path         /var/log/pods/*/*.log
        Parser       docker
        Tag          kube.*

    [OUTPUT]
        Name         stdout
        Match        *
