apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.10.1
          # env:
          #   # - name: ELASTICSEARCH_HOSTS
          #   #   value: "http://elasticsearch:9200"
          #   - name: ELASTICSEARCH_USERNAME
          #     value: "admin13"
          #   - name: ELASTICSEARCH_PASSWORD
          #     value: "admin13"
          env:
            - name: elasticsearch.hosts
              value: "http://elasticsearch.default.svc.cluster.local:9200"
            - name: xpack.security.enabled
              value: "false"
          ports:
            - containerPort: 5601 # Kibana's web UI port
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: default
spec:
  ports:
    - port: 5601
      targetPort: 5601
  selector:
    app: kibana
