apiVersion: v1
kind: Service
metadata:
  name: stock-service
  namespace: default
  # selector:
  #   app: stock-app
spec:
  type: NodePort #LoadBalancer
  #type: LoadBalancer
  selector:
    app: stock-app
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 8090 #containerPort and targetPort have to match
      nodePort: 30001
