server:
  port: 8090
spring:
#  datasource:
#    #url: jdbc:mysql://localhost/stock
#    url: jdbc:mysql://localhost:3306/stock
#    username: root
#    password: root

#  jpa:
#    hibernate:
#      ddl-auto: update
#      #ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  ##this is for h2
  ############################################
  datasource:
    url: jdbc:h2:mem:stock
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      