server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://stock-db:3306/stock
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    #database-platform: org.hibernate.dialect.MySQLDialect
# Uncomment if you're using MongoDB
#  data:
#    mongodb:
#      host: mongodb_container
#      port: 27017
#      database: stock
