server:
  port: 8090
spring:
  datasource:
#    url: jdbc:mysql://stock-db:3306/stock
#    url: jdbc:mysql://192.168.128.5:3306/stock
    url: ${DB_URL:jdbc:mysql://localhost:3306/stock} # Default to localhost if not set
    username: ${DB_USERNAME:root}                     # Default username
    password: ${DB_PASSWORD:root}                     # Default password
#    username: root
#    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        
#        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
cors:
  allowed:
    origin: ${CORS_URL:http://localhost:4200}
