server:
  port: 8090
spring:
  datasource:
#    url: jdbc:mysql://stock-db:3306/stock
#    url: jdbc:mysql://192.168.128.5:3306/stock
    url: ${DB_URL:jdbc:mysql://localhost:3306/stock} # Default to localhost if not set
    username: ${DB_USERNAME:root}                     # Default username
    password: ${DB_PASSWORD:root}                     # Default password
#    username: root
#    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        
#        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true


    #database-platform: org.hibernate.dialect.MySQLDialect
# Uncomment if you're using MongoDB
#  data:
#    mongodb:
#      host: mongodb_container
#      port: 27017
#      database: stock
